BEGIN TRANSACTION;
CREATE TABLE `sources` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`server`	INTEGER NOT NULL,
	`remote_path`	TEXT NOT NULL DEFAULT '/',
	`local_path`	TEXT NOT NULL
);
CREATE TABLE `settings` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`key`	TEXT NOT NULL,
	`value`	TEXT
);
CREATE TABLE `servers` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`hostname`	TEXT NOT NULL,
	`local_path`	TEXT NOT NULL
);
CREATE TABLE `products` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`remote_path`	TEXT NOT NULL
);
COMMIT;
